# Пример конфигурации для пакетной обработки
name: example_batch
description: "на основе ленинского района воронежа"

# Пути к директориям
input_dir: "scripts/exported"
output_dir: "converted/exported"

# Настройки обработки

#количество обрабатываемых файлов
# limit 100 

retry_count: 3
parallel: 1
generate_html_report: true
ai_provider: anthropic
max_iterations: 3

# Пользовательские параметры для подстановки
params:
  startDate: "'2023-01-01 00:00:000'::timestamp"
  endDate: "'2023-12-31 00:00:000'::timestamp"
  userTypeID: "1"
  region: "'Europe'"
  topRank: "10"
  categoryID: "5"
  minSalesAmount: "1000"
