SELECT MAX(CASE WHEN DATEDIFF(DAY, DATEADD(YEAR, 14, wpc.BIRTHDATE), wan.A_DATE_REG) > 0 
 and DATEDIFF(DAY, DATEADD(YEAR, 18, wpc.BIRTHDATE), wan.A_DATE_REG) < 0 THEN 
       CASE WHEN workinf.OUID IS NOT NULL OR link.A_ID IS NOT NULL OR wr.OUID IS NOT NULL THEN 1 ELSE 0 END
  ELSE 1 END)
  FROM wm_petition wp
INNER JOIN WM_APPEAL_NEW wan
  ON wan.ouid = wp.OUID
  INNER JOIN WM_PERSONAL_CARD wpc
  ON wpc.OUID = wp.A_MSPHOLDER
LEFT JOIN WM_WORKSINFO workinf
  ON workinf.PERSONOUID = wpc.OUID
AND (workinf.A_STATUS = 10 OR workinf.A_STATUS IS NULL)
  AND DATEDIFF(DAY, workinf.DATEOFEMP, wan.A_DATE_REG) >= 0
  AND DATEDIFF(DAY, wan.A_DATE_REG,  ISNULL(workinf.DATEOFSACKING, wan.A_DATE_REG)) >= 0
LEFT JOIN WM_RELATEDRELATIONSHIPS wr
  ON wr.A_ID1 = wpc.OUID
  AND (wr.A_STATUS = 10 OR wr.A_STATUS IS null)
  AND DATEDIFF(DAY, wr.A_BEGIN_DATE, wan.A_DATE_REG) > 0

LEFT JOIN SPR_LINK_APPEAL_DOC link
  INNER JOIN WM_ACTDOCUMENTS wa
  ON wa.OUID = link.TOID
  AND ISNULL(wa.A_STATUS, 10) = 10
  INNER JOIN PPR_DOC pd
  ON pd.A_ID = wa.DOCUMENTSTYPE
  AND ISNULL(pd.A_STATUS, 10) = 10
  AND pd.GUID = '87827b1e-ff60-42ec-bc43-e2871b28b19c'
  ON link.FROMID = wp.OUID
  AND DATEDIFF(DAY, wa.ISSUEEXTENSIONSDATE, wan.A_DATE_REG) >= 0
  AND DATEDIFF(DAY, wan.A_DATE_REG, ISNULL(wa.COMPLETIONSACTIONDATE, wan.A_DATE_REG)) >= 0
WHERE wp.ouid = {params.petitionId}
  AND (wan.A_STATUS = 10 OR wan.A_STATUS IS NULL)
  AND (wpc.A_STATUS = 10 OR wpc.A_STATUS IS NULL)