    SELECT MAX(CASE WHEN wa.OUID IS NULL OR wo.A_OUID is NULL THEN 1
    ELSE CASE WHEN slad.A_ID IS NOT NULL AND link.A_ID IS NOT NULL THEN 1 ELSE 0 END END)
    FROM wm_petition wp
    INNER JOIN WM_APPEAL_NEW wan
    ON wan.ouid = wp.OUID

    LEFT JOIN WM_RELATEDRELATIONSHIPS wr
    INNER JOIN SPR_GROUP_ROLE sgr
    ON sgr.OUID = wr.A_RELATED_RELATIONSHIP
    AND sgr.A_COD IN ('wife', 'husband')
    ON wr.A_ID1 = wp.A_MSPHOLDER
    AND ISNULL(wr.A_STATUS, 10) = 10

    LEFT JOIN WM_ACTDOCUMENTS wa
    INNER JOIN PPR_DOC pd
    ON pd.A_ID = wa.DOCUMENTSTYPE
    AND ISNULL(pd.A_STATUS, 10) = 10
    AND pd.GUID = '63a721:10e084af5bb:-7f2a' /*договор соц найма*/
    ON wa.PERSONOUID IN (wp.A_MSPHOLDER, wr.A_ID2)
    AND isnull(wa.A_STATUS, 10) = 10
    AND DATEDIFF(DAY, wa.ISSUEEXTENSIONSDATE, wan.A_DATE_REG) >= 0
    AND DATEDIFF(DAY, wan.A_DATE_REG, ISNULL(wa.COMPLETIONSACTIONDATE, wan.A_DATE_REG)) >= 0

    LEFT JOIN WM_OWNING wo
    INNER JOIN SPR_VID_OWNER vid
    ON vid.A_OUID = wo.A_OWNING_VID
    AND vid.A_CODE = 'owner'
    INNER JOIN PurposeBuilding pb
    ON pb.A_OUID = wo.A_PURPOSE_BUILDING
    AND ISNULL(pb.A_STATUS, 10) = 10
    AND pb.GUID IN ('720b9df5-3e92-47be-9c3f-cec5d0a8712d', '6e2fb235-8d56-4189-9e38-805e83cfa1c0', '7e5b063d-5fc1-4f50-bc1f-84dcfb03578e')
    ON wo.A_OWNER_ID = wp.A_MSPHOLDER
    AND ISNULL(wa.A_STATUS, 10) = 10

    LEFT JOIN SPR_LINK_APPEAL_DOC slad
    INNER JOIN WM_ACTDOCUMENTS wa1
    ON wa1.OUID = slad.TOID
    AND ISNULL(wa1.A_STATUS, 10) = 10
    INNER JOIN PPR_DOC pd1
    ON pd1.A_ID = wa1.DOCUMENTSTYPE
    AND ISNULL(pd1.A_STATUS, 10) = 10
    AND pd1.GUID = '63a721:10e084af5bb:-7f2a'
    ON slad.FROMID = wp.OUID
    AND DATEDIFF(DAY, wa1.ISSUEEXTENSIONSDATE, wan.A_DATE_REG) >= 0
    AND DATEDIFF(DAY, wan.A_DATE_REG, ISNULL(wa1.COMPLETIONSACTIONDATE, wan.A_DATE_REG)) >= 0

    LEFT JOIN SPR_LINK_APPEAL_DOC link
    INNER JOIN WM_ACTDOCUMENTS wa2
    ON wa2.OUID = link.TOID
    AND ISNULL(wa2.A_STATUS, 10) = 10
    INNER JOIN PPR_DOC pd2
    ON pd2.A_ID = wa2.DOCUMENTSTYPE
    AND ISNULL(pd2.A_STATUS, 10) = 10
    AND pd2.GUID IN ('06a849a1-80ca-44c8-9edb-c3de6f47b95c', 'b986b92b-8bb3-4d62-8e70-61ec9e370593')
    AND (ISNULL(wa2.A_NEPRIGODNODLYAPROZHIV, 0) = 1 OR ISNULL(wa2.A_PRIZNANAVARIJNYM, 0) = 1 OR pd2.GUID != 'b986b92b-8bb3-4d62-8e70-61ec9e370593')
    ON link.FROMID = wp.OUID
    AND wa2.PERSONOUID = wp.A_MSPHOLDER
    AND DATEDIFF(DAY, wa2.ISSUEEXTENSIONSDATE, wan.A_DATE_REG) >= 0
    AND DATEDIFF(DAY, wan.A_DATE_REG, ISNULL(wa2.COMPLETIONSACTIONDATE, wan.A_DATE_REG)) >= 0

    WHERE wp.ouid = {params.petitionId}
    AND (wan.A_STATUS = 10 OR wan.A_STATUS IS NULL)