SELECT MAX(CASE WHEN (wp.A_DATE_AN_OBJ IS NOT NULL AND slad.A_ID IS NOT NULL) OR ISNULL(wp.A_ADD_AN_OBJ, 0) = 0
  THEN 1 
  ELSE 0 end )
  FROM wm_petition wp
INNER JOIN WM_APPEAL_NEW wan
  ON wan.ouid = wp.OUID
LEFT JOIN SPR_LINK_APPEAL_DOC slad
  INNER JOIN WM_ACTDOCUMENTS wa
  ON wa.OUID =slad.TOID
  AND (wa.A_STATUS = 10 OR wa.A_STATUS IS NULL)
  INNER JOIN PPR_DOC pd
  ON pd.A_ID = wa.DOCUMENTSTYPE
  AND (pd.A_STATUS = 10 OR pd.A_STATUS IS NULL)
  AND pd.GUID = '160288ff-772e-4f2c-b18e-3f1f2ccc38dd'
  ON slad.FROMID = wp.OUID
WHERE wp.ouid = {params.petitionId}
  AND (wan.A_STATUS = 10 OR wan.A_STATUS IS NULL)